name: Code Review Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Create virtual environment
      run: python3 -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install dependencies in virtual environment
      run: pip install -r requirements.txt

    - name: Deactivate virtual environment
      run: deactivate

    - name: Run code review
      run: |
        flake8 .

    - name: Run install.sh script
      run: |
        chmod +x install.sh
        ./install.sh
